name: Generate Backup IPTV

on:
workflow_dispatch:
inputs:
username:
required: true
type: string
password:
required: true
type: string

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Generate final2.m3u
    run: |
      cp base.m3u final2.m3u

      sed -i "s/{USERNAME}/${{ github.event.inputs.username }}/g" final2.m3u
      sed -i "s/{PASSWORD}/${{ github.event.inputs.password }}/g" final2.m3u

  - name: Commit
    run: |
      git config user.name "github-actions"
      git config user.email "actions@github.com"

      git add final2.m3u

      git commit -m "Update final2.m3u" || exit 0

      git push
