name: Generate Backup IPTV

on:
  workflow_dispatch:
    inputs:
      username:
        description: IPTV Username
        required: true
      password:
        description: IPTV Password
        required: true

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate final.m3u & final2.m3u
        env:
          USERNAME: ${{ github.event.inputs.username }}
          PASSWORD: ${{ github.event.inputs.password }}
        run: |
          for file in final.m3u final2.m3u; do
            cp base.m3u "$file"

            sed -i "s/{USERNAME}/${USERNAME}/g" "$file"
            sed -i "s/{PASSWORD}/${PASSWORD}/g" "$file"
          done

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add final.m3u final2.m3u

          git diff --cached --quiet && exit 0

          git commit -m "Update final.m3u and final2.m3u"

          git push
