name: Update IPTV List

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Google Chrome and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        sudo apt-get install -y google-chrome-stable

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium undetected-chromedriver

    - name: Run IPTV Update Script
      run: |
        python update_iptv.py headless
